
/** Static content */
export const StaticData = {
fillInput: "Please fill out this field",
Meta_title:"TGI Fridays stores in the USA | TGI Fridays",
Meta_description:"Find your local TGI Fridays store with our store locator. See opening times, directions and information for our stores across the USA.",
locator_breadcrumb:"Store Locator",
UseMyLocation:"Use my location",
BrandName:"TGI Fridays",
miles:"miles",
tempClosed:"Temporarily Closed",
Days:"Days",
Hours:"Hours",
Minutes:"Minutes",
Seconds:"Seconds",
getDirection:"Get Directions",
AllLocationText:"View All Location",
PageNotFound:"404 Error",
PageNotFoundDescription:"The page you are looking for does not exist.",
CookieButtonText:"Got IT",
DayOfWeek:"Day of the Week",
ReopenMessage:"Message - The store is temporarily closed. It will reopen at",
Telephone:"Telephone",
SeeAllGoogleReviews:"See All Google Reviews",
Home:"Home",
GetTheApp:"Get the App",
Faqs:"FAQ's",
Closed:"Closed",
LocationResults:"Location results",
FindsTGIFridaysnearme:"Find a TGI Fridays near me",
ListView: "List View",
MapView: "Map View",
NoStoresFound: "Sorry, No Location Found For Related Search"
}